### ISSUE TITLE
Main-Template blocking LetsEncrypt host

### ISSUE THREAD

**Issue by yoshimo** [KodoPengin/GameIndustry-hosts-Template#12]
In Main-Template you exempt ```r3.o.lencr.org``` in the LE section but list it in org.
I think this hostname is harmless and blocking it even harmful, remove it.

**Comment by KodoPengin** [comment]
Thank you.

Will be fixed in the next update. Was an blocked entry slipped in by mistake.

**Comment by KodoPengin** [comment]
See https://github.com/KodoPengin/GameIndustry-hosts-Template/issues/16#issuecomment-1364609361

**Comment by KodoPengin** [comment]
See - https://github.com/KodoPengin/GameIndustry-hosts-Template/issues/16#issuecomment-1364609361

**Comment by awebeer256** [comment]
> See - [#16 (comment)](https://github.com/KodoPengin/GameIndustry-hosts-Template/issues/16#issuecomment-1364609361)

I don't see how that comment addresses the issue. `r3.o.lencr.org` is still in the blocklist over a year later, and if you have OCSP checking enabled in your browser (and you should!), this results in **your own website being blocked** (`www.gameindustry.eu`), along with many, *many* other legitimate sites. Here's just some of the ones I experienced:

```
man.archlinux.org
discussion.fedoraproject.org
www.freedesktop.org
www.gnu.org
search.nixos.org
help.ubuntu.com
manpages.ubuntu.com
```

If my understanding is correct, the complete list is a significant fraction of ALL sites that get their TLS certificates from Let's Encrypt and that don't use OCSP stapling.
