### ISSUE TITLE
 e6913.dscx.akamaiedge.net  breaks ocsp.entrust.net

### ISSUE THREAD

**Issue by yoshimo** [KodoPengin/GameIndustry-hosts-Template#16]
i think we should not block ocsp servers for security reasons.

**Comment by KodoPengin** [comment]
Correct
Well... my Pi is installed, will check the next time

**Comment by KodoPengin** [comment]
> i think we should not block ocsp servers for security reasons.

Do you know where you noticed the entrust issue?

**Comment by KodoPengin** [comment]
Nevermind, found a source -  Will be fixed next update
