### ISSUE TITLE
cs570.wac.deltacdn.net as CNAME for cfg.gog.com causes "offline" messages

### ISSUE THREAD

**Issue by yoshimo** [KodoPengin/GameIndustry-hosts-Template#19]
```cs570.wac.deltacdn.net``` is the alias for ```cfg.gog.com``` .
When this is blacklisted the client complains about problems and won't import new games into the list.

Also is a cname for ```images.gog.com```.

**Comment by KodoPengin** [comment]
Thanks, wIll be fixed in the next update
