### ISSUE TITLE
False Positive: `camo.githubusercontent.com`

### ISSUE THREAD

**Issue by j-moriarti** [KodoPengin/GameIndustry-hosts-Template#2]
Hello! the domain `camo.githubusercontent.com` is blocked in **Main-Template**. it is used by github to [convert an image of a url to an anonymized one](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/about-anonymized-urls).

Example: [this image link](https://www.gameindustry.eu/images/header/gi_logo_2021.webp) will be converted to [this url](https://camo.githubusercontent.com/8565cd077d4290184d5d39f6843b45d0d7312cecd1287b71082901c8c46a2f38/68747470733a2f2f7777772e67616d65696e6475737472792e65752f696d616765732f6865616465722f67695f6c6f676f5f323032312e77656270) (by deploying the following html code in github):
`<img src="https://www.gameindustry.eu/images/header/gi_logo_2021.webp" />`
<img src="https://www.gameindustry.eu/images/header/gi_logo_2021.webp" />

**Comment by KodoPengin** [comment]
> 
> 
> Hello! the domain `camo.githubusercontent.com` is blocked in **Main-Template**. it is used by github to [convert an image of a url to an anonymized one](https://docs.github.com/en/github/authenticating-to-github/keeping-your-account-and-data-secure/about-anonymized-urls).
> 
> Example: [this image link](https://www.gameindustry.eu/images/header/gi_logo_2021.webp) will be converted to [this url](https://camo.githubusercontent.com/8565cd077d4290184d5d39f6843b45d0d7312cecd1287b71082901c8c46a2f38/68747470733a2f2f7777772e67616d65696e6475737472792e65752f696d616765732f6865616465722f67695f6c6f676f5f323032312e77656270) (by deploying the following html code in github):
> `<img src="https://www.gameindustry.eu/images/header/gi_logo_2021.webp" />`
> ![](https://camo.githubusercontent.com/8565cd077d4290184d5d39f6843b45d0d7312cecd1287b71082901c8c46a2f38/68747470733a2f2f7777772e67616d65696e6475737472792e65752f696d616765732f6865616465722f67695f6c6f676f5f323032312e77656270)

Hello back, and thanks for leaving a nothice here. Next update will published beginning of the next month. The entry will be disabled.
