### ISSUE TITLE
Unblock Bing

### ISSUE THREAD

**Issue by m3thm4th** [KodoPengin/GameIndustry-hosts-Template#21]
The Main Template list blocks `www.bing.com`, which is not a malicious domain in itself.

**Comment by KodoPengin** [comment]
Malicious not, but Bing is blocked for several tied telemetry/functions/callbacks. It is also a service responsible for advertising.

This will remain in future, as privacy is systematically eroded by Microsoft Corporation. Bing has to be unblocked manually. 

At the moment i'm collecting new points for the FAQ (bing is noted) and will overhaul the hosts-files header.
