### ISSUE TITLE
d1dxcvubdbe4ji.cloudfront.net breaks EpicGame Store videos

### ISSUE THREAD

**Issue by yoshimo** [KodoPengin/GameIndustry-hosts-Template#25]
Videos for games are hosted onmedia-cdn.epicgames.com which is an alias for d1dxcvubdbe4ji.cloudfront.net .
Therefore the videos fail to load.

**Comment by KodoPengin** [comment]
I'll check this again in the next time and correct it if necessary. Thanks for the hint

**Comment by KodoPengin** [comment]
Checked - Will be fixed in the next update i publish today. Thanks as always ;]
