### ISSUE TITLE
Will you not continue?

### ISSUE THREAD

**Issue by gallegonovato** [KodoPengin/GameIndustry-hosts-Template#26]
Good afternoon:

You are not going to continue with the hosts?

The truth is that it is a tremendous pity.

A hug and thank you for your help and time.

**Comment by KodoPengin** [comment]
Sorry and good evening/afternoon.
I will continue, no worry.

However, I have taken time off, a move behind me and currently also not really motivated. Nevertheless, new updates have been added to the website and an update for the hosts with a few fixes and new titles is also in the works.

**Comment by gallegonovato** [comment]
Good afternoon:

Sorry for taking so long to respond. 

Glad to hear you are well and that you are going to continue with the hosts.

I missed them. Especially for Android as there are millions more connections all the time.

Best regards and thanks for your time and help.
