### ISSUE TITLE
dl.google.com is required for Widevine Updates

### ISSUE THREAD

**Issue by yoshimo** [KodoPengin/GameIndustry-hosts-Template#27]
Widevine CDM to watch streaming services is loaded over ```dl.google.com``` on MediaTV boxes running Kodi.

**Comment by KodoPengin** [comment]
Widevine is also used to deliver advertising and data mining.

See https://gameindustry.eu/katalog/google-llc/widevine/ with few examples. Therefore the service will remain partially blocked
