### ISSUE TITLE
The GOG&Galaxy SDK case

### ISSUE THREAD

**Issue by yoshimo** [KodoPengin/GameIndustry-hosts-Template#28]
GoG  offers an SDK for game developers to allow achievement tracking and social features.
Your list interferes with the function of this SDK and a few GalaxyClient features.
Here the blocked hostnames and what they are used for:

`notifications.gog.com`
Just pings you about incoming friend requests, wishlist games being on sale

```
notifications-pusher.gog.com
notifications-pusher-aws.gog.com
```
notifies the clients about incoming messages, chat , friends coming online, thelike`

`gameplay.gog.com`
This is used to track achievments and playtime by the games and the client

`presence.gog.com`
Makes sure that you that you are seen as online by your friends by sending a keep alive every 5 minutes.

Neither of these fall into an analytics, unwanted tracking or advertising category.

**Comment by KodoPengin** [comment]
Is not investigated further, filter list does exactly what it is supposed to do
