### ISSUE TITLE
block complete gstatic.com ?

### ISSUE THREAD

**Issue by schmaller** [KodoPengin/GameIndustry-hosts-Template#3]
Hello !
With commit #5f54627f943ba9859271b7e1772666379334ea3e you blocked the whole gstatic.com domain.
Isn't  that way too much?
i guess without access to e.g. connectivitycheck.gstatic.com a majority of android smartphones will stop working properly.
Apart from that: thanks for your good work! 
Best regards, Daniel

**Comment by KodoPengin** [comment]
Hello Schmaller (Daniel) and thanks for your question.

From tests it's enough to block just "0.0.0.0 gstatic.com" to prevent Google Callbacks in relation to Steam (well, it's the only service i know with such behaviour). You can compare this to Firefox Captive Portal. During a week i had over 15000 blocked attempts in my PI-Hole Query from Steam alone for this address.

From steam.exe outgoing connections:

`IPv4 examples:
172.217.168.67
172.217.18.99
142.250.186.35
142.250.185.227
172.217.168.67
216.58.212.131
216.58.215.227
142.250.185.195

Host: http://gstatic.com/generate_204
Endpoint: gstaticadssl.l.google.com

GET /generate_204 HTTP/1.1
user-agent: Valve/Steam HTTP Client 1.0 (0)
Host: gstatic.com
Accept: text/html,*/*;q=0.9
accept-charset: ISO-8859-1,utf-8,*;q=0.7
Accept-Encoding: identity

HTTP/1.1 204 No Content
Date: Wed, 13 Oct 2021 12:56:16 GMT
Content-Length: 0`

Everything else for GStatic, like Google Captcha, Google Fonts and should continue to work. In that case it would really be too much ;]

Connectivitycheck.android.com (from Android Template) i use also with host and PI-Hole without problems. And yes, they are the same like MicrosoftNCSI checks for Windows.

You can give feedback again.

Regards
