### ISSUE TITLE
s3.amazonaws.com is a bit broad

### ISSUE THREAD

**Issue by yoshimo** [KodoPengin/GameIndustry-hosts-Template#30]
```s3.amazonaws.com``` is used for storage for quite a few services.
I couldn't download howtos we ordered online because they are stored on Amazon Web Services.

This domain is commented out  for ```Weed Inc: Idle Tycoon```  but blocked for ```Cash, Inc.``` so maybe you should go for subdomains as you did for  ```Foodpia Tycoon - Idle restaurant```?

**Comment by KodoPengin** [comment]
I will update Android lists soon with the note that they will not be maintained for the time being. This will only happen with the purchase of a new mobile device.

S3 is enabled in the main template.
