### ISSUE TITLE
Amazon S3, again s3-3-w.amazonaws.com

### ISSUE THREAD

**Issue by yoshimo** [KodoPengin/GameIndustry-hosts-Template#31]
```s3-3-w.amazonaws.com``` , i'd say  it is the same problem as  #30 , just a different hostname
it is a cname for images hosted on ```polarsteps.s3.amazonaws.com```

**Comment by KodoPengin** [comment]
`s3.amazonaws.com` is unblocked in Android files, as well as the main-template and gaming template. Subdomains should be not affected.
