### ISSUE TITLE
Remove lencr.org subdomains from lists, it's an OCSP data provider

### ISSUE THREAD

**Issue by dorsiflexion** [KodoPengin/GameIndustry-hosts-Template#36]
The block lists contain several entries from `lencr.org`. This domain belongs to [Let's Encrypt](https://letsencrypt.org/docs/lencr.org/) and is providing OCSP data (`o.lencr.org`) and Certificate Revocation Lists (`c.lencr.org`). In other words, this is a security provider, among others used for TLS security. Therefore, `lencr.org` and its subdomains should absolutely not be blocked, but instead be removed from the lists.

**Comment by KodoPengin** [comment]
Thanks for the note but the entry will stay. See

https://github.com/KodoPengin/GameIndustry-hosts-Template/issues/16
