### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by kinsi55** [KodoPengin/GameIndustry-hosts-Template#38]
`ns.exitgames.com` should be removed

It is required by various titles for Multiplayer to work (We were here, golf with your friends and operation tango just to name a few)

**Comment by KodoPengin** [comment]
Yes, i know. Exitgames/Photon Engine.

Well, connections are specified for each product. If I were to delete the entry, the entries would no longer be complete. In addition, ns.exitgames.com is enabled and is not blocked.
