### ISSUE TITLE
False positive: `use.fontawesome.com`

### ISSUE THREAD

**Issue by remyabel2** [KodoPengin/GameIndustry-hosts-Template#6]
Fontawesome is used for font rendering on many websites. Shouldn't be blocked by default.

**Comment by KodoPengin** [comment]
Will be fixed in the next update.

**Comment by KodoPengin** [comment]
Well, updated for but it's and wasn't a false positive. It's some kind of absolutely unnecessary connection like Google Fonts who were often in criticism for the same mechanic in relation to usertracking.
