### ISSUE TITLE
2 new domains

### ISSUE THREAD

**Issue by begin-theadventure** [KodoPengin/GameIndustry-hosts-Template#8]
crashreporting.gameforge.com -Gameforge client.
splitgate.bugsplat.com -Splitgate, bugsplat is "Crash and Error Reporting".

**Comment by KodoPengin** [comment]
Thanks, i will add them for the next update.

Is it still possible to trace the origin of the two entries?

**Comment by begin-theadventure** [comment]
I'm not sure.
I use OpenSnitch and have seen those domains trying to connect when I was using the Gameforge client and playing Splitgate.
That's all I can answer.

**Comment by KodoPengin** [comment]
Sorry for the very late response. I'll look at the title the days. Depending on the result, found entries will be added on the website and in the block lists.
